name: bookstar_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  flutter_speed_dial: ^7.0.0
  image_picker: ^0.8.7+3
  path_provider: ^2.1.5
  table_calendar: ^3.0.9
  webview_flutter: ^4.10.0
  url_launcher: ^6.1.8
  http: ^1.2.2
  flutter_launcher_icons: ^0.14.2
  # flutter_secure_storage: ^9.2.2
  sign_in_with_apple: ^6.1.4
  provider: ^6.1.2
  gap: ^3.0.1
  kakao_flutter_sdk: ^1.9.7+3
  fluttertoast: ^8.2.12
  equatable: ^2.0.7
  permission_handler: ^12.0.0+1
  dio: ^5.8.0+1
  go_router: ^14.8.1
  flutter_dotenv: ^5.2.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/App_LOGO_zoomout.png"

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/images/
    - .env

  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/Pretendard-Regular.otf